"""add conversations table and conversation_id to question_logs

Revision ID: 78a393f36c95
Revises: 1cd64842772c
Create Date: 2026-07-05 15:32:24.122411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78a393f36c95'
down_revision: Union[str, Sequence[str], None] = '1cd64842772c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.add_column('question_logs', sa.Column('conversation_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_question_logs_conversation_id'), 'question_logs', ['conversation_id'], unique=False)
    op.create_foreign_key(None, 'question_logs', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_logs', type_='foreignkey')
    op.drop_index(op.f('ix_question_logs_conversation_id'), table_name='question_logs')
    op.drop_column('question_logs', 'conversation_id')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
