"""question_feedbacks tablosuna comment kolonu eklendi

Revision ID: d884625bb712
Revises: 6e2bd48a7c74
Create Date: 2026-07-04 14:51:11.632173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd884625bb712'
down_revision: Union[str, Sequence[str], None] = '6e2bd48a7c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_feedbacks', sa.Column('comment', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_feedbacks', 'comment')
    # ### end Alembic commands ###
